CREATE DATABASE authdb;

CREATE USER uauth WITH PASSWORD '2gSgu136txww*66WaAq';
CREATE USER uvault WITH PASSWORD 'dede23dgwu2376fytsw';


GRANT ALL PRIVILEGES ON DATABASE vaultdb TO uvault;
GRANT ALL PRIVILEGES ON DATABASE authdb TO uauth;


\connect vaultdb
GRANT ALL PRIVILEGES ON SCHEMA public TO uloyalty;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO uvault;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO uvault;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO uvault;

\connect authdb
GRANT ALL PRIVILEGES ON SCHEMA public TO uauth;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO uauth;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO uauth;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON FUNCTIONS TO uauth;
