-- +goose Up
-- +goose StatementBegin
CREATE TABLE vault_items
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    data_type      SMALLINT    NOT NULL,
    group_id       BIGINT      NOT NULL,
    encrypted_blob BYTEA       NOT NULL,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at     TIMESTAMPTZ
);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE IF EXISTS vault_items;
-- +goose StatementEnd
